#!/usr/bin/env python3
"""async_comprehension for python
"""
import asyncio
import random
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """get the ten elements generated by the
    async_generator function added in a list

    Yields:
        List[float]: return List of 10 random float numbers
    """
    return [i async for i in async_generator()]
