# Generated by Django 4.2.17 on 2024-12-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
